version: '3.8'
services:

  postgresql-vtb-web-db:
    container_name: postgresql-vtb-web-db
    image: phoekoby/postgres-vtb-db:1.0-SNAPSHOT
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=vtb
    ports:
      - "5432:5432"
    networks:
      - internal


  rabbit-mq-vtb-web:
    container_name: rabbit-mq-vtb-web
    image: phoekoby/vtb-web-rabbitmq:0.0.1-SNAPSHOT
    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: user
    ports:
      - '15672:15672'
    networks:
      - internal



  vtb-transact-management:
    image: phoekoby/transact-management:0.0.1-SNAPSHOT
    restart: on-failure
    networks:
      - internal
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_CLOUD_CONFIG_URI: http://vtb-configuration-server:8765
    depends_on:
      vtb-eureka-server:
        condition: service_healthy



  vtb-marketplace-management:
    image: phoekoby/marketplace-management:0.0.1-SNAPSHOT
    restart: on-failure
    networks:
      - internal
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_CLOUD_CONFIG_URI: http://vtb-configuration-server:8765
    depends_on:
      vtb-eureka-server:
        condition: service_healthy



  vtb-gamification-management:
    image: phoekoby/gamification-management:0.0.1-SNAPSHOT
    restart: on-failure
    networks:
      - internal
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_CLOUD_CONFIG_URI: http://vtb-configuration-server:8765
    depends_on:
      vtb-eureka-server:
        condition: service_healthy



  vtb-configuration-server:
    image: phoekoby/configuration:0.0.3-SNAPSHOT
    networks:
      - internal
    ports:
      - "8765:8765"
    healthcheck:
      test: curl --fail http://vtb-configuration-server:8765/eureka-server/prod
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgresql-vtb-web-db:
        condition: service_started


  vtb-eureka-server:
    image: phoekoby/eureka-server:0.0.2-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_CLOUD_CONFIG_URI: http://vtb-configuration-server:8765
    networks:
      - internal
    healthcheck:
      test: curl --fail http://vtb-eureka-server:8761/
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      vtb-configuration-server:
        condition: service_healthy
    ports:
      - "8761:8761"



  vtb-gateway:
    image: phoekoby/client:1.0-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_CLOUD_CONFIG_URI: http://vtb-configuration-server:8765
    networks:
      - internal
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      vtb-eureka-server:
        condition: service_healthy


networks:
  internal:
