export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const SHOP_ROUTE = '/shop'
export const REGISTRATION_ROUTE = '/registration'
export const PROFILE_ROUTE = '/profile'
export const PRODUCT_ROUTE = '/products'
