version: '3.8'
services:
  postgresql-vtb-web-db:
    container_name: postgresql-vtb-web-db
    image: postgres:latest
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./db/init.sql:/docker-entry-point-initdb.d/init.sql
  adminer-postgresql-vtb-web-db:
    container_name: adminer-postgresql-vtb-web-db
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 127.0.0.1:5050:80



