version: '3.8'
services:
  rabbit-mq-vtb-web:
    container_name: rabbit-mq-vtb-web
    image: bitnami/rabbitmq:latest
    ports:
      - '15672:15672'
    volumes:
      - 'rabbitmqstats_data:/bitnami'